# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0  # Должна стоять последняя версия! Иначе будут проблемы при запуске.
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.3
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v1.10.1  # Use the latest stable version from the repository
#    hooks:
#      - id: mypy

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [ python ]
        require_serial: true
        args:
          [
            "-rn", # Only display messages
            "-sn", # Don't display the score
          ]
