# Generated by Django 5.1 on 2024-08-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_remove_additionaloption_tour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeofchargeservice',
            name='service_name',
            field=models.CharField(default='Default Service', max_length=50),
        ),
        migrations.AlterField(
            model_name='additionaloption',
            name='option_name',
            field=models.CharField(default='Default Option', max_length=50),
        ),
        migrations.AlterField(
            model_name='freeofchargeservice',
            name='service_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
