# Generated by Django 5.1 on 2024-09-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tours", "0005_alter_tour_ship_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionaloption",
            name="option_description",
            field=models.TextField(blank=True, default="Default Description"),
        ),
        migrations.AlterField(
            model_name="freeofchargeservice",
            name="service_description",
            field=models.TextField(blank=True, default="Default Description"),
        ),
        migrations.AlterField(
            model_name="photo",
            name="description",
            field=models.TextField(blank=True, default="Default Description"),
        ),
        migrations.AlterField(
            model_name="tour",
            name="cost_options",
            field=models.TextField(blank=True, default="Default Cost Options"),
        ),
    ]
