# Generated by Django 5.1 on 2024-09-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_rental', '0009_alter_bike_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='bike_photos/'),
        ),
    ]
