# Generated by Django 5.1 on 2024-09-09 10:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bike_rental", "0012_bikebrand_logo"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Order",
            new_name="BikeOrder",
        ),
    ]
