# Generated by Django 5.1 on 2024-09-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_rental', '0013_bikemodel_fuel_consumption_bikemodel_seat_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikemodel',
            name='max_speed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
