# Generated by Django 5.1 on 2024-09-13 09:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bike_rental", "0015_alter_bike_bike_model"),
        ("bike_rental", "0015_rename_clearance_bikemodel_wheel_size"),
    ]

    operations = []
