# Generated by Django 5.1 on 2024-09-16 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_rental', '0017_biketype_bikemodel_bike_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikemodel',
            name='bike_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bike_models', to='bike_rental.biketype'),
        ),
    ]
