# Generated by Django 5.1 on 2024-09-16 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_rental', '0018_alter_bikemodel_bike_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biketype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bike_types/'),
        ),
    ]
