# Generated by Django 5.1 on 2024-09-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_rental', '0019_alter_biketype_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RidePurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ridepurpose/')),
            ],
        ),
        migrations.AddField(
            model_name='bikemodel',
            name='ride_purposes',
            field=models.ManyToManyField(blank=True, related_name='bike_models', to='bike_rental.ridepurpose'),
        ),
    ]
