# Generated by Django 5.1 on 2024-09-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_rental', '0020_ridepurpose_bikemodel_ride_purposes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biketype',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='biketype',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
