# Generated by Django 5.1 on 2024-09-16 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike_rental', '0022_alter_biketype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biketype',
            options={'ordering': ['order']},
        ),
    ]
