# Generated by Django 5.1 on 2024-09-16 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike_rental', '0024_alter_biketype_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bikemodel',
            old_name='wheel_size',
            new_name='clearance',
        ),
    ]
