# Generated by Django 5.1 on 2024-09-21 21:16

import django.db.models.deletion
from django.db import migrations, models
import datetime



class Migration(migrations.Migration):

    dependencies = [
        ('bike_rental', '0026_bikeprovider_providerservice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='owner',
            new_name='bike_provider',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='price_per_day',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='price_per_month',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='price_per_week',
        ),
        migrations.AddField(
            model_name='bike',
            name='date_production',
            field=models.DateField(default=datetime.date(2015, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bike',
            name='deposit_type',
            field=models.CharField(default=2015, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bike',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day1_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('day2_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('day3_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('day4_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('day5_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('week_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='bike_rental.bike')),
            ],
        ),
    ]
