# Generated by Django 5.1 on 2024-09-26 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_rental', '0028_alter_bike_date_production_alter_bike_deposit_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promouter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_pyte', models.CharField(max_length=255)),
                ('partner_id', models.CharField(max_length=255)),
                ('comition_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('qr_codes', models.TextField()),
                ('bike_orders', models.ManyToManyField(blank=True, related_name='promouters', to='bike_rental.bikeorder')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promouter_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
