# Generated by Django 5.1 on 2024-09-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_rental', '0029_promouter'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikeorder',
            name='first_source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bikeorder',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='promouter',
            name='utm_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
