# Generated by Django 5.1 on 2024-09-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_rental', '0030_bikeorder_first_source_bikeorder_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promouter',
            name='partner_id',
        ),
        migrations.AlterField(
            model_name='promouter',
            name='promo_pyte',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
