# Generated by Django 5.1 on 2024-09-27 12:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_rental', '0031_remove_promouter_partner_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['bike', 'season', 'duration']},
        ),
        migrations.AddField(
            model_name='price',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='duration',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('close_date', models.DateField()),
                ('bike_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='bike_rental.bikeprovider')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.AddField(
            model_name='price',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='bike_rental.season'),
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('bike', 'season', 'duration')},
        ),
        migrations.RemoveField(
            model_name='price',
            name='day1_price',
        ),
        migrations.RemoveField(
            model_name='price',
            name='day2_price',
        ),
        migrations.RemoveField(
            model_name='price',
            name='day3_price',
        ),
        migrations.RemoveField(
            model_name='price',
            name='day4_price',
        ),
        migrations.RemoveField(
            model_name='price',
            name='day5_price',
        ),
        migrations.RemoveField(
            model_name='price',
            name='month_price',
        ),
        migrations.RemoveField(
            model_name='price',
            name='week_price',
        ),
    ]
