# Generated by Django 5.1 on 2024-09-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_rental', '0032_alter_price_options_price_cost_price_duration_season_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(choices=[('High', 'High season'), ('Normal', 'Normal season'), ('Low', 'Low season')], max_length=100),
        ),
    ]
