# Generated by Django 5.1 on 2024-09-27 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_rental', '0033_alter_season_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='price',
            name='duration',
            field=models.IntegerField(choices=[(1, '1 day'), (2, '2 days'), (3, '3 days'), (4, '4 days'), (5, '5 days'), (6, '7 days'), (7, '1 week'), (14, '2 weeks'), (21, '3 weeks'), (30, '1 month')], default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
