# Generated by Django 5.1 on 2024-09-27 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_rental', '0034_alter_price_cost_alter_price_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='bike_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike_rental.bikeprovider'),
        ),
    ]
