# Generated by Django 5.1 on 2024-09-27 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike_rental', '0035_alter_bike_bike_provider'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='price',
            unique_together=set(),
        ),
    ]
