# Generated by Django 5.1 on 2024-09-27 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_rental', '0036_alter_price_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bike_rental.season'),
        ),
    ]
