# Generated by Django 5.1 on 2024-09-28 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike_rental', '0037_alter_price_season'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('bike', 'season', 'duration')},
        ),
    ]
