# Generated by Django 5.1 on 2024-09-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_rental', '0038_alter_price_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promouter',
            name='qr_codes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
