# Generated by Django 5.1 on 2024-09-30 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_rental', '0039_alter_promouter_qr_codes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promouter',
            name='qr_codes',
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_link', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='qr_codes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('promouter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='bike_rental.promouter')),
            ],
        ),
    ]
